import logging
import json
from agents.base_agent import BaseAgent

logger = logging.getLogger(__name__)

class ReportWriterAgent(BaseAgent):
    """
    Agent responsible for synthesizing final structured summaries.
    Demonstrates forced tool usage (`tool_choice`) to guarantee
    strictly structured JSON output on every invocation.
    """

    def __init__(self, **kwargs):
        super().__init__(
            agent_name="ReportWriter",
            max_iterations=5,  # Forced tools usually finish in 1-2 turns
            **kwargs,
        )
        self.final_summary = None

    def get_system_prompt(self) -> str:
        return """You are the final Report Writer Agent. 
Your sole objective is to take the provided input data from the trading system
and synthesize a clean, structured JSON summary via the `generate_summary` tool.

Do not ask questions. Do not attempt to use other tools. 
You MUST call the `generate_summary` tool to submit your final report."""

    def get_tools(self) -> list[dict]:
        """Provides exactly one tool that the agent must use."""
        return [
            {
                "name": "generate_summary",
                "description": "Submits the final structured reporting summary.",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "executive_summary": {
                            "type": "string",
                            "description": "A 1-2 sentence high-level summary."
                        },
                        "key_metrics": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "List of the most critical metrics or factors."
                        },
                        "final_recommendation": {
                            "type": "string",
                            "enum": ["BUY", "SELL", "HOLD", "REVIEW"],
                            "description": "The ultimate system recommendation."
                        }
                    },
                    "required": ["executive_summary", "key_metrics", "final_recommendation"],
                },
            }
        ]

    def get_tool_choice(self) -> dict | None:
        """
        FORCE the model to call generate_summary specifically.
        This guarantees the agent won't return random natural language text.
        """
        return {"type": "tool", "name": "generate_summary"}

    def execute_tool(self, tool_name: str, tool_input: dict) -> dict:
        """
        Capture the JSON payload generated by the forced tool_choice.
        """
        if tool_name == "generate_summary":
            logger.info(f"[{self.agent_name}] Captured forced summary execution.")
            
            # Stash the payload so the system can extract it easily.
            # In a real system, you might emit an event or save to a DB.
            self.final_summary = tool_input
            
            # Once the tool successfully executes, we tell Claude it was a success.
            # Claude will then see this and trigger 'end_turn'.
            return {"status": "success", "message": "Summary stored successfully. You may conclude your turn."}
            
        raise ValueError(f"Unknown tool called: {tool_name}")

    def validate_result(self, result: dict) -> tuple[bool, str]:
        """
        Ensure Claude doesn't just stop but actually generated the summary.
        """
        if not self.final_summary:
            return False, "You terminated without calling the forced generate_summary tool."
            
        return True, ""
        
    def _parse_result(self, text: str) -> dict:
        """
        Since we forced tool use, we ignore Claude's final conversational text 
        and extract the strictly parsed JSON we stashed during tool execution.
        """
        if self.final_summary:
            return self.final_summary
        return super()._parse_result(text)
